### PR TITLE
Emit an include_dir variable at build-time

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
I'm experimenting with a SpiderMonkey bump in `mozjs_sys`, and this would allow me to make the crate that holds the vendored SM code to link against `encoding_c_mem` just as it would for any other crate, even using the headers from it transparently without revendoring them in `mozjs_sys`.

**Comment by hsivonen** [comment]
The `cargo:include-dir` makes sense to me. (Where is `cargo:include-dir` documented?)

Can you explain the self-referential `links` manifest entry? The [docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) suggest using it for declaring C dependencies. Why is the self-referential `links` needed?

**Comment by nox** [comment]
> This metadata is passed to the build scripts of dependent packages. For example, if libbar depends on libfoo, then if libfoo generates key=value as part of its metadata, then the build script of libbar will have the environment variables DEP_FOO_KEY=value.

This only applies if the manifest has a `links` key, otherwise Cargo will schedule the dependent build script independently from the dependency build script, not propagating the metadata from the latter to the former.

If you are wary of a unique `links` key, I guess I could make it `encoding_c_mem_0_2_5`, or something like that, but do note that `encoding_c_mem` is indeed emitting `no_mangle` symbols, so AFAIK multiple incompatible `encoding_c_mem` versions in a single crate tree would lead to linking errors, which means the `links` thing is a good idea anyway.

**Comment by hsivonen** [comment]
OK. I don't have experience in this area, but I trust this does the right thing. Thanks.

I take it that `encoding_c` should do the same thing?

**Comment by hsivonen** [comment]
Published as 0.2.5 on crates.io.

**Comment by nox** [comment]
> I take it that `encoding_c` should do the same thing?

I think so yes, I didn't even realise this was also a crate, I was just trying to build mozjs by making it use the headers from this crate from crates.io. mozjs doesn't use `encoding_c` at all right?

**Comment by hsivonen** [comment]
> mozjs doesn't use `encoding_c` at all right?

It does, without actually including the headers, use parts that in retrospect should be in `encoding_c_mem` but for legacy reasons aren't. (UTF-8 validation and ASCII validation.)

**Comment by nox** [comment]
So it just declares the prototypes of the functions in the `encoding_c` crate in tree?

**Comment by hsivonen** [comment]
> So it just declares the prototypes of the functions in the `encoding_c` crate in tree?

Yes, for the two entry points used from SpiderMonkey. They are declared in a way that agrees with the C header included on the Gecko side.

**Pull request merged**
